services:
  - type: web
    name: dtpennyroute
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: STORAGE_PATH
        value: /opt/render/project/src/storage
